<a href="https://colab.research.google.com/github/giogio400/iqburst/blob/main/Copy_of_h4_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **დავალებები: Numpy ბიბლიოთეკა**

## 1. მასივის შექმნა და ინდექსირება
- **მასივის შექმნა:**  
  შექმენით 1D numpy მასივი, რომელიც შეიცავს 20 ელემენტს (შეგიძლიათ გამოიყენოთ `np.arange` ან `np.linspace`).

- **ინდექსირება:**  
  დაბეჭდეთ:
  - მასივის პირველი 5 ელემენტი,
  - მასივის ბოლო 5 ელემენტი,
  - ყოველი მეორე ელემენტი.

- **2D მასივი:**  
  შექმენით 2D მასივი ზომით (4, 5) შემთხვევითი მთელი რიცხვებით (გამოიყენეთ `np.random.randint`).

- **წვდომა ელემენტებზე:**  
  - დაბეჭდეთ კონკრეტული რიგი (მაგ., მესამე რიგი),
  - კონკრეტული სვეტი (მაგ., მეოთხე სვეტი),
  - მე-2 რიგში და მე-3 სვეტში მდებარე ელემენტი.

In [ ]:
import numpy as np
print("=" * 50)
print("1. მასივის შექმნა და ინდექსირება (1D)")
print("=" * 50)
# 1D მასივი 20 ელემენტით (1-დან 20-მდე)
array_1d = np.arange(1, 21)
print(f"\nმასივი: {array_1d}")
# პირველი 5 ელემენტი
print(f"\nპირველი 5 ელემენტი: {array_1d[:5]}")
# ბოლო 5 ელემენტი
print(f"ბოლო 5 ელემენტი: {array_1d[-5:]}")
# ყოველი მეორე ელემენტი
print(f"ყოველი მეორე ელემენტი: {array_1d[::2]}")
print("\n" + "=" * 50)
print("2. 2D მასივი და წვდომა ელემენტებზე")
print("=" * 50)
# 2D მასივი (4, 5) შემთხვევითი რიცხვებით (0-დან 100-მდე)
array_2d = np.random.randint(0, 100, size=(4, 5))
print(f"\n2D მასივი (4x5):\n{array_2d}")
# მესამე რიგი (index 2)
print(f"\nმესამე რიგი: {array_2d[2]}")
# მეოთხე სვეტი (index 3)
print(f"მეოთხე სვეტი: {array_2d[:, 3]}")
# მე-2 რიგში და მე-3 სვეტში მდებარე ელემენტი (index [1, 2])
print(f"მე-2 რიგი, მე-3 სვეტი: {array_2d[1, 2]}")
print("\n" + "=" * 50)
print("დამატებითი მაგალითები")
print("=" * 50)
# პირველი 2 რიგი და პირველი 3 სვეტი
print(f"\nპირველი 2 რიგი, პირველი 3 სვეტი:\n{array_2d[:2, :3]}")
# ყველა რიგი, მხოლოდ ბოლო სვეტი
print(f"\nყველა რიგი, ბოლო სვეტი: {array_2d[:, -1]}")
# მხოლოდ ლუწი რიგები
print(f"\nლუწი რიგები (0, 2):\n{array_2d[::2]}")

1. მასივის შექმნა და ინდექსირება (1D)

მასივი: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

პირველი 5 ელემენტი: [1 2 3 4 5]
ბოლო 5 ელემენტი: [16 17 18 19 20]
ყოველი მეორე ელემენტი: [ 1  3  5  7  9 11 13 15 17 19]

2. 2D მასივი და წვდომა ელემენტებზე

2D მასივი (4x5):
[[41 80 76 29 53]
 [84 41 70 57 49]
 [65 66 57 63 43]
 [55 12 29 81 44]]

მესამე რიგი: [65 66 57 63 43]
მეოთხე სვეტი: [29 57 63 81]
მე-2 რიგი, მე-3 სვეტი: 70

დამატებითი მაგალითები

პირველი 2 რიგი, პირველი 3 სვეტი:
[[41 80 76]
 [84 41 70]]

ყველა რიგი, ბოლო სვეტი: [53 49 43 44]

ლუწი რიგები (0, 2):
[[41 80 76 29 53]
 [65 66 57 63 43]]


## 2. მასივების მანიპულირება
- **ფორმის შეცვლა (Reshaping):**  
  შექმენით 1D მასივი 20 ელემენტით და გარდაქმნეთ მასივი ფორმაში (4, 5) `reshape()`-ის გამოყენებით.

- **Flatten:**  
  გარდაქმნეთ 2D მასივი 1D ფორმატში `flatten()` ან `ravel()`-ის საშუალებით.

- **stacking:**  
  შექმენით ორი იგივე ზომის 2D მასივი და მოახდინეთ მათი:
  - ჰორიზონტალური stacking (`np.hstack`),
  - ვერტიკალური stacking (`np.vstack`).

In [ ]:
import numpy as np

print("=" * 70)
print("NumPy - მასივების მანიპულირება")
print("=" * 70)

# ============================================================
# 1. ფორმის შეცვლა (Reshaping)
# ============================================================

print("\n\n" + "=" * 70)
print("1. ფორმის შეცვლა (Reshaping)")
print("=" * 70)

# 1D მასივი 20 ელემენტით
array_1d = np.arange(1, 21)
print(f"\n1D მასივი (20 ელემენტი):")
print(f"მასივი: {array_1d}")
print(f"ფორმა: {array_1d.shape}")

# Reshape (4, 5)-ში
array_reshaped = array_1d.reshape(4, 5)
print(f"\nReshape-ილი (4, 5):")
print(f"მასივი:\n{array_reshaped}")
print(f"ფორმა: {array_reshaped.shape}")

# სხვა მაგალითი - (2, 2, 5)
array_reshaped_3d = array_1d.reshape(2, 2, 5)
print(f"\nReshape-ილი (2, 2, 5) - 3D:")
print(f"მასივი:\n{array_reshaped_3d}")
print(f"ფორმა: {array_reshaped_3d.shape}")

# ============================================================
# 2. Flatten და Ravel
# ============================================================

print("\n\n" + "=" * 70)
print("2. Flatten და Ravel")
print("=" * 70)

# 2D მასივი
array_2d = np.array([[1, 2, 3, 4, 5],
                     [6, 7, 8, 9, 10],
                     [11, 12, 13, 14, 15],
                     [16, 17, 18, 19, 20]])
print(f"\n2D მასივი (4x5):")
print(f"მასივი:\n{array_2d}")
print(f"ფორმა: {array_2d.shape}")

# Flatten() - ახალი კოპია
flattened = array_2d.flatten()
print(f"\nFlatten()-ილი მასივი:")
print(f"მასივი: {flattened}")
print(f"ფორმა: {flattened.shape}")
print(f"ეს არის კოპია (ახალი მეხსიერება)")

# Ravel() - view (არ იქმნება კოპია)
raveled = array_2d.ravel()
print(f"\nRavel()-ილი მასივი:")
print(f"მასივი: {raveled}")
print(f"ფორმა: {raveled.shape}")
print(f"ეს არის view (იგივე მეხსიერება)")

# Flatten vs Ravel განსხვავება
print(f"\n--- Flatten vs Ravel განსხვავება ---")
print(f"Flatten აბრუნებს კოპიას (owns data)")
print(f"Ravel აბრუნებს view-ს (არ owns data)")

# შეცვლა და შედეგი
raveled[0] = 999
print(f"\nRavel-ის პირველი ელემენტი შეიცვალა 999-ზე:")
print(f"ორიგინალური 2D მასივი (შეიცვალა!):\n{array_2d}")

# ============================================================
# 3. Stacking - ჰორიზონტალური (hstack)
# ============================================================

print("\n\n" + "=" * 70)
print("3. Stacking - ჰორიზონტალური (np.hstack)")
print("=" * 70)

# პირველი 2D მასივი (2x3)
array_a = np.array([[1, 2, 3],
                    [4, 5, 6]])
print(f"\nმასივი A (2x3):")
print(f"მასივი:\n{array_a}")
print(f"ფორმა: {array_a.shape}")

# მეორე 2D მასივი (2x3)
array_b = np.array([[7, 8, 9],
                    [10, 11, 12]])
print(f"\nმასივი B (2x3):")
print(f"მასივი:\n{array_b}")
print(f"ფორმა: {array_b.shape}")

# Hstack - გვერდიგვერდ (სვეტები გაერთიანება)
hstacked = np.hstack((array_a, array_b))
print(f"\nHStack (ჰორიზონტალური - გვერდიგვერდ):")
print(f"მასივი:\n{hstacked}")
print(f"ფორმა: {hstacked.shape}")
print(f"ახსნა: (2x3) + (2x3) = (2x6)")

# ============================================================
# 4. Stacking - ვერტიკალური (vstack)
# ============================================================

print("\n\n" + "=" * 70)
print("4. Stacking - ვერტიკალური (np.vstack)")
print("=" * 70)

# იგივე მასივი A და B
print(f"\nმასივი A (2x3):\n{array_a}")
print(f"\nმასივი B (2x3):\n{array_b}")

# Vstack - ერთმეორის ზეწოდ (რიგები გაერთიანება)
vstacked = np.vstack((array_a, array_b))
print(f"\nVStack (ვერტიკალური - ერთმეორის ზეწოდ):")
print(f"მასივი:\n{vstacked}")
print(f"ფორმა: {vstacked.shape}")
print(f"ახსნა: (2x3) + (2x3) = (4x3)")

# ============================================================
# 5. დამატებითი: Concatenate (უფრო რთული)
# ============================================================

print("\n\n" + "=" * 70)
print("5. დამატებითი: Concatenate")
print("=" * 70)

# Concatenate axis=0 (ვერტიკალურად) = vstack
concat_0 = np.concatenate((array_a, array_b), axis=0)
print(f"\nConcatenate (axis=0 - ვერტიკალურად):")
print(f"მასივი:\n{concat_0}")
print(f"ფორმა: {concat_0.shape}")

# Concatenate axis=1 (ჰორიზონტალურად) = hstack
concat_1 = np.concatenate((array_a, array_b), axis=1)
print(f"\nConcatenate (axis=1 - ჰორიზონტალურად):")
print(f"მასივი:\n{concat_1}")
print(f"ფორმა: {concat_1.shape}")

# ============================================================
# 6. დამატებითი: Stack (ახალი axis)
# ============================================================

print("\n\n" + "=" * 70)
print("6. დამატებითი: Stack (ახალი axis)")
print("=" * 70)

# Stack - 3D მასივი შექმნა
stacked_3d = np.stack((array_a, array_b), axis=0)
print(f"\nStack (3D მასივი):")
print(f"მასივი:\n{stacked_3d}")
print(f"ფორმა: {stacked_3d.shape}")

# ============================================================
# 7. რეალური მაგალითი: ხელებში ყველა ერთად
# ============================================================

print("\n\n" + "=" * 70)
print("7. რეალური მაგალითი: ყველა ერთად")
print("=" * 70)

print("\nსცენარი: გვაქვს 20 ელემენტი, რომელიც უნდა გადავაკეთოთ სხვადსხვა ფორმაში")

# ნაბიჯი 1: 1D მასივი შექმნა
original = np.arange(1, 21)
print(f"\n1. 1D მასივი (20 ელემენტი):")
print(f"   {original}")

# ნაბიჯი 2: Reshape
reshaped = original.reshape(4, 5)
print(f"\n2. Reshape (4, 5):")
print(f"{reshaped}")

# ნაბიჯი 3: გაყოფა ორ ნაწილად
top_half = reshaped[:2, :]  # პირველი 2 რიგი
bottom_half = reshaped[2:, :]  # ბოლო 2 რიგი
print(f"\n3. გაყოფა ორ ნაწილად:")
print(f"ზედა (2x5):\n{top_half}")
print(f"ქვედა (2x5):\n{bottom_half}")

# ნაბიჯი 4: Vstack მათი დასაბრუნებლად
combined = np.vstack((top_half, bottom_half))
print(f"\n4. VStack (მიმდებარე შედეგი):")
print(f"{combined}")

# ნაბიჯი 5: Flatten
flattened_result = combined.flatten()
print(f"\n5. Flatten:")
print(f"   {flattened_result}")

# ============================================================
# 8. ხელმძღვანელი ცხრილი
# ============================================================

print("\n\n" + "=" * 70)
print("ხელმძღვანელი ცხრილი")
print("=" * 70)

table = """
┌──────────────────┬──────────────────┬──────────────────────┐
│ ფუნქცია          │ შედეგი           │ აღწერა               │
├──────────────────┼──────────────────┼──────────────────────┤
│ reshape()        │ ახალი ფორმა      │ ელემენტების გარდა   │
│                  │                  │ დაქცევა              │
├──────────────────┼──────────────────┼──────────────────────┤
│ flatten()        │ 1D მასივი (კოპია)│ 2D → 1D              │
│                  │                  │ ახალი მეხსიერება     │
├──────────────────┼──────────────────┼──────────────────────┤
│ ravel()          │ 1D მასივი (VIEW) │ 2D → 1D              │
│                  │                  │ იგივე მეხსიერება     │
├──────────────────┼──────────────────┼──────────────────────┤
│ hstack()         │ გვერდიგვერდ      │ სვეტები გაერთიანება  │
│                  │                  │ (axis=1)             │
├──────────────────┼──────────────────┼──────────────────────┤
│ vstack()         │ ერთმეორის ზეწოდ  │ რიგები გაერთიანება   │
│                  │                  │ (axis=0)             │
├──────────────────┼──────────────────┼──────────────────────┤
│ concatenate()    │ axis-ის მიხედვით │ უფრო რთული          │
│                  │                  │ (axis დაკ)           │
├──────────────────┼──────────────────┼──────────────────────┤
│ stack()          │ ახალი axis       │ 3D ან ზემოთ          │
└──────────────────┴──────────────────┴──────────────────────┘
"""
print(table)

# ============================================================
# 9. ვიზუალური მაგალითი
# ============================================================

print("\n\n" + "=" * 70)
print("9. ვიზუალური მაგალითი - ხელებში ყველა")
print("=" * 70)

# მასივები
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print(f"\nA (2x2):\n{A}\n")
print(f"B (2x2):\n{B}\n")

print("აქ რა ხდება:")
print(f"  Reshape: 4 ელ. → (2x2)")
print(f"  Flatten: (2x2) → 4 ელ.")
print(f"  HStack A+B: (2x2) + (2x2) → (2x4)")
print(f"  VStack A+B: (2x2) + (2x2) → (4x2)")

# ============================================================
# 10. სადილემა: რა აირჩიო?
# ============================================================

print("\n\n" + "=" * 70)
print("10. რა აირჩიო?")
print("=" * 70)

decision_tree = """
რა უნდა გავაკეთო?

┌─ ფორმის შეცვლა? ──→ reshape()
│
├─ 2D → 1D?
│  ├─ კოპია სჭირდება? ──→ flatten()
│  └─ view? ──→ ravel()
│
└─ ორი მასივი გაერთიანება?
   ├─ გვერდიგვერდ? ──→ hstack()
   └─ ერთმეორის ზეწოდ? ──→ vstack()
"""
print(decision_tree)

NumPy - მასივების მანიპულირება


1. ფორმის შეცვლა (Reshaping)

1D მასივი (20 ელემენტი):
მასივი: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
ფორმა: (20,)

Reshape-ილი (4, 5):
მასივი:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
ფორმა: (4, 5)

Reshape-ილი (2, 2, 5) - 3D:
მასივი:
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
ფორმა: (2, 2, 5)


2. Flatten და Ravel

2D მასივი (4x5):
მასივი:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
ფორმა: (4, 5)

Flatten()-ილი მასივი:
მასივი: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
ფორმა: (20,)
ეს არის კოპია (ახალი მეხსიერება)

Ravel()-ილი მასივი:
მასივი: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
ფორმა: (20,)
ეს არის view (იგივე მეხსიერება)

--- Flatten vs Ravel განსხვავება ---
Flatten აბრუნებს კოპიას (owns data)
Ravel აბრუნებს view-ს (არ owns data)

Ravel-ის პირველი ელემენტი შეიცვალა 999-ზე:
ორიგინალური 2D

## 3. მათემატიკური ოპერაციები
- **მასივის შექმნა:**  
  შექმენით 1D მასივი შემთხვევითი რიცხვებით.

- **ოპერაციები:**  
  - გამოთვალეთ თითოეული ელემენტის კვადრატული მნიშვნელობა,
  - გამოთვალეთ მასივის ელემენტების ჯამი (ელემენტური ოპერაციებით და numpy ფუნქციით).


- **ტრიგონომეტრიული ფუნქციები:**  
  გამოითვალეთ მასივის თითოეული ელემენტის sine და cosine მნიშვნელობები.

In [ ]:
import numpy as np

print("=" * 70)
print("NumPy - მათემატიკური ოპერაციები")
print("=" * 70)

# ============================================================
# 1. მასივის შექმნა შემთხვევითი რიცხვებით
# ============================================================

print("\n\n" + "=" * 70)
print("1. მასივის შექმნა შემთხვევითი რიცხვებით")
print("=" * 70)

# შემთხვევითი რიცხვები 1-დან 100-მდე
np.random.seed(42)  # განმეორებადი შედეგებისთვის
array = np.random.randint(1, 100, size=10)
print(f"\nშემთხვევითი მასივი (1-100): {array}")

# შემთხვევითი ათწილადი რიცხვები (0-1)
array_float = np.random.rand(10)
print(f"შემთხვევითი ათწილადი: {np.round(array_float, 2)}")

# ============================================================
# 2. კვადრატული მნიშვნელობა
# ============================================================

print("\n\n" + "=" * 70)
print("2. კვადრატული მნიშვნელობა (Squaring)")
print("=" * 70)

# მარტივი მასივი
simple_array = np.array([1, 2, 3, 4, 5])
print(f"\nორიგინალური მასივი: {simple_array}")

# კვადრატი - მეთოდი 1: გამრავლება თავისზე
squared_1 = simple_array * simple_array
print(f"\nქვადრატი (* თავისზე): {squared_1}")

# კვადრატი - მეთოდი 2: np.square()
squared_2 = np.square(simple_array)
print(f"ქვადრატი (np.square()): {squared_2}")

# კვადრატი - მეთოდი 3: ** ოპერატორი
squared_3 = simple_array ** 2
print(f"ქვადრატი (** 2): {squared_3}")

# რეალური მაგალითი
print(f"\nრეალური მაგალითი (შემთხვევითი რიცხვები):")
print(f"ორიგინალური: {array}")
print(f"კვადრატი: {np.square(array)}")

# ============================================================
# 3. ელემენტების ჯამი
# ============================================================

print("\n\n" + "=" * 70)
print("3. ელემენტების ჯამი (Sum)")
print("=" * 70)

print(f"\nმასივი: {array}")

# მეთოდი 1: np.sum()
sum_np = np.sum(array)
print(f"\nნამრავლი (np.sum()): {sum_np}")

# მეთოდი 2: Python-ის sum()
sum_python = sum(array)
print(f"ნამრავლი (sum()): {sum_python}")

# მეთოდი 3: მეთოდი (ობიექტის მეთოდი)
sum_method = array.sum()
print(f"ნამრავლი (.sum()): {sum_method}")

# ============================================================
# 4. სხვა მახასიათებელი ოპერაციები
# ============================================================

print("\n\n" + "=" * 70)
print("4. სხვა მახასიათებელი ოპერაციები")
print("=" * 70)

print(f"\nმასივი: {array}")
print(f"\nსტატისტიკა:")
print(f"  საშუალო (mean): {np.mean(array):.2f}")
print(f"  მედიანა (median): {np.median(array):.2f}")
print(f"  მინიმალური: {np.min(array)}")
print(f"  მაქსიმალური: {np.max(array)}")
print(f"  ჯამი: {np.sum(array)}")
print(f"  ნამრავლი (product): {np.prod(array)}")
print(f"  სტანდარტული გადახრა: {np.std(array):.2f}")
print(f"  ვარიანსი: {np.var(array):.2f}")

# ============================================================
# 5. ელემენტური ოპერაციები (Element-wise)
# ============================================================

print("\n\n" + "=" * 70)
print("5. ელემენტური ოპერაციები")
print("=" * 70)

arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([2, 3, 4, 5, 6])

print(f"\nმასივი 1: {arr1}")
print(f"მასივი 2: {arr2}")

# შეკრება
addition = arr1 + arr2
print(f"\nშეკრება (+): {addition}")

# გამოკლება
subtraction = arr1 - arr2
print(f"გამოკლება (-): {subtraction}")

# გამრავლება
multiplication = arr1 * arr2
print(f"გამრავლება (*): {multiplication}")

# გაყოფა
division = arr1 / arr2
print(f"გაყოფა (/): {np.round(division, 2)}")

# მოდულო
modulo = arr1 % arr2
print(f"მოდულო (%): {modulo}")

# ხარისხი
power = arr1 ** arr2
print(f"ხარისხი (**): {power}")

# ============================================================
# 6. ტრიგონომეტრიული ფუნქციები (Trigonometric)
# ============================================================

print("\n\n" + "=" * 70)
print("6. ტრიგონომეტრიული ფუნქციები")
print("=" * 70)

# კუთხეები რადიანებში
angles_rad = np.array([0, np.pi/6, np.pi/4, np.pi/3, np.pi/2])
print(f"\nკუთხეები (რადიანი): {np.round(angles_rad, 4)}")

# კუთხეები გრადუსებში (დემო)
angles_deg = np.degrees(angles_rad)
print(f"კუთხეები (გრადუსი): {np.round(angles_deg, 2)}")

# Sine
sine_values = np.sin(angles_rad)
print(f"\nSine მნიშვნელობები: {np.round(sine_values, 4)}")

# Cosine
cosine_values = np.cos(angles_rad)
print(f"Cosine მნიშვნელობები: {np.round(cosine_values, 4)}")

# Tangent
tangent_values = np.tan(angles_rad)
print(f"Tangent მნიშვნელობები: {np.round(tangent_values, 4)}")

# ============================================================
# 7. ტრიგონომეტრიული ფუნქციების სამაგალითო ცხრილი
# ============================================================

print("\n\n" + "=" * 70)
print("7. ტრიგონომეტრიული ფუნქციების სამაგალითო ცხრილი")
print("=" * 70)

angles = np.array([0, 30, 45, 60, 90])  # გრადუსი
angles_rad = np.radians(angles)  # რადიანში გადა

print(f"\n{'კუთხე (°)': <12} {'რადიანი': <12} {'sin': <10} {'cos': <10} {'tan': <10}")
print("-" * 54)

for angle_deg, angle_r in zip(angles, angles_rad):
    s = np.sin(angle_r)
    c = np.cos(angle_r)
    t = np.tan(angle_r)
    print(f"{angle_deg: <12.0f} {angle_r: <12.4f} {s: <10.4f} {c: <10.4f} {t: <10.4f}")

# ============================================================
# 8. ფესვები და ხარისხები
# ============================================================

print("\n\n" + "=" * 70)
print("8. ფესვები და ხარისხები")
print("=" * 70)

numbers = np.array([1, 4, 9, 16, 25, 36, 49, 64, 81, 100])
print(f"\nრიცხვები: {numbers}")

# კვადრატული ფესვი
sqrt = np.sqrt(numbers)
print(f"\nკვადრატული ფესვი: {sqrt}")

# კუბური ფესვი
cbrt = np.cbrt(numbers)
print(f"კუბური ფესვი: {np.round(cbrt, 2)}")

# ხარისხი
power_2 = np.power(numbers, 2)
print(f"ხარისხი (^2): {power_2}")

# ============================================================
# 9. ლოგარითმი და ექსპონენტა
# ============================================================

print("\n\n" + "=" * 70)
print("9. ლოგარითმი და ექსპონენტა")
print("=" * 70)

positive_nums = np.array([1, 2, 5, 10, 100])
print(f"\nრიცხვები: {positive_nums}")

# ბუნებრივი ლოგარითმი (ln)
ln = np.log(positive_nums)
print(f"\nბუნებრივი ლოგარითმი (ln): {np.round(ln, 4)}")

# ლოგარითმი base 10
log10 = np.log10(positive_nums)
print(f"ლოგარითმი (base 10): {np.round(log10, 4)}")

# ლოგარითმი base 2
log2 = np.log2(positive_nums)
print(f"ლოგარითმი (base 2): {np.round(log2, 4)}")

# ექსპონენტა (e^x)
exp = np.exp(np.array([0, 1, 2]))
print(f"\nექსპონენტა (e^x): {np.round(exp, 4)}")

# ============================================================
# 10. აბსოლუტური მნიშვნელობა
# ============================================================

print("\n\n" + "=" * 70)
print("10. აბსოლუტური მნიშვნელობა")
print("=" * 70)

mixed = np.array([-5, -2, 0, 3, 7, -10])
print(f"\nრიცხვები: {mixed}")

absolute = np.abs(mixed)
print(f"აბსოლუტური მნიშვნელობა: {absolute}")

# ============================================================
# 11. რეალური მაგალითი: მართკუთხედის ფართობი
# ============================================================

print("\n\n" + "=" * 70)
print("11. რეალური მაგალითი: მართკუთხედის ფართობი")
print("=" * 70)

length = np.array([5, 10, 15, 20])
width = np.array([3, 4, 6, 8])

print(f"\nდაკ: {length}")
print(f"სიგანე: {width}")

area = length * width
print(f"ფართობი: {area}")

total_area = np.sum(area)
print(f"სულ ფართობი: {total_area}")

# ============================================================
# 12. რეალური მაგალითი: კვადრატის დიაგონალი
# ============================================================

print("\n\n" + "=" * 70)
print("12. რეალური მაგალითი: კვადრატის დიაგონალი")
print("=" * 70)

side = np.array([3, 4, 5, 6])
print(f"\nმხარის სიგრძე: {side}")

# დიაგონალი = მხარე * sqrt(2)
diagonal = side * np.sqrt(2)
print(f"დიაგონალი: {np.round(diagonal, 2)}")

# ============================================================
# 13. ხელმძღვანელი ცხრილი
# ============================================================

print("\n\n" + "=" * 70)
print("13. ხელმძღვანელი ცხრილი - მათემატიკური ოპერაციები")
print("=" * 70)

table = """
┌──────────────────┬─────────────────────────────────────┐
│ ფუნქცია          │ აღწერა                              │
├──────────────────┼─────────────────────────────────────┤
│ np.square()      │ კვადრატი                            │
│ np.sqrt()        │ კვადრატული ფესვი                   │
│ np.cbrt()        │ კუბური ფესვი                        │
│ np.power()       │ ხარისხი                             │
│ np.sum()         │ ჯამი                                │
│ np.prod()        │ ნამრავლი                            │
│ np.mean()        │ საშუალო                             │
│ np.median()      │ მედიანა                             │
│ np.std()         │ სტანდარტული გადახრა                │
│ np.sin()         │ სინუსი                              │
│ np.cos()         │ კოსინუსი                            │
│ np.tan()         │ ტანგენსი                            │
│ np.log()         │ ბუნებრივი ლოგარითმი (ln)           │
│ np.log10()       │ ლოგარითმი (base 10)                │
│ np.log2()        │ ლოგარითმი (base 2)                 │
│ np.exp()         │ ექსპონენტა (e^x)                    │
│ np.abs()         │ აბსოლუტური მნიშვნელობა             │
│ np.degrees()     │ რადიანი → გრადუსი                   │
│ np.radians()     │ გრადუსი → რადიანი                   │
└──────────────────┴─────────────────────────────────────┘
"""
print(table)

# ============================================================
# 14. სწრაფი ცხრილი: ოპერატორები
# ============================================================

print("\n\n" + "=" * 70)
print("14. სწრაფი ცხრილი - ელემენტური ოპერატორები")
print("=" * 70)

operators_table = """
┌───────────┬──────────────────────────────────┐
│ ოპერატორი │ აღწერა                           │
├───────────┼──────────────────────────────────┤
│ +         │ შეკრება                           │
│ -         │ გამოკლება                         │
│ *         │ გამრავლება (ელემენტური)          │
│ /         │ გაყოფა (ელემენტური)              │
│ //        │ მთელი გაყოფა                      │
│ %         │ მოდულო (ნაშთი)                   │
│ **        │ ხარისხი                          │
│ ==        │ ტოლობა                           │
│ !=        │ უტოლობა                          │
│ <, >      │ ნაკლები, მეტი                    │
│ <=, >=    │ ნაკლები/ტოლი, მეტი/ტოლი         │
└───────────┴──────────────────────────────────┘
"""
print(operators_table)

NumPy - მათემატიკური ოპერაციები


1. მასივის შექმნა შემთხვევითი რიცხვებით

შემთხვევითი მასივი (1-100): [52 93 15 72 61 21 83 87 75 75]
შემთხვევითი ათწილადი: [0.87 0.6  0.71 0.02 0.97 0.83 0.21 0.18 0.18 0.3 ]


2. კვადრატული მნიშვნელობა (Squaring)

ორიგინალური მასივი: [1 2 3 4 5]

ქვადრატი (* თავისზე): [ 1  4  9 16 25]
ქვადრატი (np.square()): [ 1  4  9 16 25]
ქვადრატი (** 2): [ 1  4  9 16 25]

რეალური მაგალითი (შემთხვევითი რიცხვები):
ორიგინალური: [52 93 15 72 61 21 83 87 75 75]
კვადრატი: [2704 8649  225 5184 3721  441 6889 7569 5625 5625]


3. ელემენტების ჯამი (Sum)

მასივი: [52 93 15 72 61 21 83 87 75 75]

ნამრავლი (np.sum()): 634
ნამრავლი (sum()): 634
ნამრავლი (.sum()): 634


4. სხვა მახასიათებელი ოპერაციები

მასივი: [52 93 15 72 61 21 83 87 75 75]

სტატისტიკა:
  საშუალო (mean): 63.40
  მედიანა (median): 73.50
  მინიმალური: 15
  მაქსიმალური: 93
  ჯამი: 634
  ნამრავლი (product): 271755942248700000
  სტანდარტული გადახრა: 25.37
  ვარიანსი: 643.64


5. ელემენტური ოპერაციები

მასივი 1: [1

## 4. მრავალგანზომილებადი მასივების ოპერაციები
- **3D მასივი:**  
  შექმენით 3D numpy მასივი ზომით (3, 4, 5) შემთხვევითი რიცხვებით.

- **სტატისტიკა**  
  გამოთვალეთ მასივი ელემენტების ჯამი სხვადასხვა ღერძების მიმართ (მაგ., სვეტი და სტრიქონი) და გამოთვალეთ მასივის საშუალო მნიშვნელობა თითოეული ღერძის მიმართ.

- **ტრანსპორტირება:**  
  გარდაქმენით მასივი (`np.transpose`).

In [ ]:
# Your code here

## 5. სორტირება, ძებნა
- **სორტირება:**  
  - შექმენით 1D მასივი.
  - გამოიყენეთ `np.sort` მასივის ელემენტების სორტირებისთვის.

- **ძებნა:**  
  გამოიყენეთ `np.where` მასივი ელემენტების ინდექსების მოსაძებნად, რომლებიც ზემოთ აღემატებიან გარკვეულ მნიშვნელობას.

- **დათვლა:**  
  ობიექტების რაოდენობა, რომლებიც აკმაყოფილებენ გარკვეულ პირობას (მაგ., `np.count_nonzero`-ის გამოყენებით).

In [ ]:
import numpy as np

print("=" * 70)
print("სორტირება, ძებნა და დათვლა")
print("=" * 70)

# ============================================================
# 1. სორტირება (Sorting)
# ============================================================

print("\n\n" + "=" * 70)
print("1. სორტირება (Sorting)")
print("=" * 70)

# 1D მასივი
array1 = np.array([45, 12, 78, 23, 56, 89, 34, 67, 11, 90])
print(f"\nორიგინალური მასივი: {array1}")

# np.sort() - ახალ მასივს აბრუნებს
sorted_array = np.sort(array1)
print(f"Sorted (ascending): {sorted_array}")

# ორიგინალური უცვლელი რჩება
print(f"ორიგინალური (უცვლელი): {array1}")

# კლებადი რიგით
sorted_descending = np.sort(array1)[::-1]
print(f"Sorted (descending): {sorted_descending}")

# ============================================================
# 2. სორტირება თავდაპირველი ინდექსებით
# ============================================================

print("\n\n" + "=" * 70)
print("2. სორტირება თავდაპირველი ინდექსებით")
print("=" * 70)

array2 = np.array([45, 12, 78, 23, 56])
print(f"\nორიგინალური მასივი: {array2}")

# np.argsort() - ინდექსების სორტირებული მასივი აბრუნებს
sorted_indices = np.argsort(array2)
print(f"Sorted Indices: {sorted_indices}")
print(f"ახსნა: {sorted_indices[0]} ინდექსে ყველაზე პატარა (12)")

# ორიგინალური მასივიდან სორტირებული ელემენტი
sorted_values = array2[sorted_indices]
print(f"Sorted Values: {sorted_values}")

# კლებადი რიგით
sorted_indices_desc = np.argsort(-array2)  # უარყოფითი
print(f"Sorted Indices (descending): {sorted_indices_desc}")

# ============================================================
# 3. 2D მასივის სორტირება
# ============================================================

print("\n\n" + "=" * 70)
print("3. 2D მასივის სორტირება")
print("=" * 70)

matrix = np.array([[45, 12, 78],
                   [23, 56, 89],
                   [34, 67, 11]])
print(f"\nორიგინალური მატრიცა:\n{matrix}")

# რიგების სორტირება (axis=1)
sorted_rows = np.sort(matrix, axis=1)
print(f"\nრიგების სორტირება (axis=1):\n{sorted_rows}")

# სვეტების სორტირება (axis=0)
sorted_cols = np.sort(matrix, axis=0)
print(f"\nსვეტების სორტირება (axis=0):\n{sorted_cols}")

# ============================================================
# 4. ძებნა (np.where)
# ============================================================

print("\n\n" + "=" * 70)
print("4. ძებნა (np.where)")
print("=" * 70)

array3 = np.array([10, 25, 30, 15, 50, 20, 45, 35, 60, 5])
print(f"\nმასივი: {array3}")

# 30-ზე მეტი ელემენტების ინდექსი
indices = np.where(array3 > 30)
print(f"\n30-ზე მეტი ელემენტების ინდექსი: {indices[0]}")

# ელემენტები
elements = array3[indices]
print(f"30-ზე მეტი ელემენტები: {elements}")

# დამატებითი მაგალითები
print(f"\n20-ზე ნაკლები ელემენტების ინდექსი: {np.where(array3 < 20)[0]}")
print(f"20-ის ტოლი ელემენტების ინდექსი: {np.where(array3 == 20)[0]}")
print(f"30-სა და 50-ს შორის: {np.where((array3 > 30) & (array3 < 50))[0]}")

# ============================================================
# 5. რთული პირობები (np.where)
# ============================================================

print("\n\n" + "=" * 70)
print("5. რთული პირობები (np.where)")
print("=" * 70)

array4 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(f"\nმასივი: {array4}")

# პირობა 1: 30-ზე მეტი
condition1 = array4 > 30
indices1 = np.where(condition1)
print(f"\n30-ზე მეტი: {indices1[0]}")

# პირობა 2: 30-დან 70-მდე
condition2 = (array4 >= 30) & (array4 <= 70)
indices2 = np.where(condition2)
print(f"30-დან 70-მდე: {indices2[0]}")
print(f"ელემენტები: {array4[indices2]}")

# ============================================================
# 6. ძებნა 2D მასივში
# ============================================================

print("\n\n" + "=" * 70)
print("6. ძებნა 2D მასივში")
print("=" * 70)

matrix2 = np.array([[10, 20, 30],
                    [40, 50, 60],
                    [70, 80, 90]])
print(f"\nმატრიცა:\n{matrix2}")

# 50-ზე მეტი ელემენტების კოორდინატი
rows, cols = np.where(matrix2 > 50)
print(f"\n50-ზე მეტი ელემენტების კოორდინატი:")
for r, c in zip(rows, cols):
    print(f"  [{r}, {c}] = {matrix2[r, c]}")

# ============================================================
# 7. დათვლა (np.count_nonzero)
# ============================================================

print("\n\n" + "=" * 70)
print("7. დათვლა (np.count_nonzero)")
print("=" * 70)

array5 = np.array([0, 1, 0, 3, 0, 5, 0, 7, 0, 9])
print(f"\nმასივი: {array5}")

# არანულოვანი ელემენტების რაოდენობა
count_nonzero = np.count_nonzero(array5)
print(f"არანულოვანი ელემენტების რაოდენობა: {count_nonzero}")

# პირობით დათვლა
array6 = np.array([10, 25, 30, 15, 50, 20, 45, 35, 60, 5])
print(f"\nმასივი: {array6}")

count_gt30 = np.count_nonzero(array6 > 30)
print(f"30-ზე მეტი ელემენტების რაოდენობა: {count_gt30}")

# ============================================================
# 8. დათვლა (np.sum ლოგიკური მასივით)
# ============================================================

print("\n\n" + "=" * 70)
print("8. დათვლა (np.sum ლოგიკური მასივით)")
print("=" * 70)

array7 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(f"\nმასივი: {array7}")

# დათვლა (np.sum)
count_gt50 = np.sum(array7 > 50)
print(f"50-ზე მეტი (np.sum): {count_gt50}")

# დათვლა (len + where)
count_gt50_where = len(np.where(array7 > 50)[0])
print(f"50-ზე მეტი (np.where): {count_gt50_where}")

# დათვლა (np.count_nonzero)
count_gt50_nonzero = np.count_nonzero(array7 > 50)
print(f"50-ზე მეტი (np.count_nonzero): {count_gt50_nonzero}")

# ============================================================
# 9. რეალური მაგალითი: სტუდენტების ქულები
# ============================================================

print("\n\n" + "=" * 70)
print("9. რეალური მაგალითი: სტუდენტების ქულები")
print("=" * 70)

scores = np.array([65, 75, 85, 45, 95, 55, 88, 72, 92, 68])
print(f"\nქულები: {scores}")

# სორტირება
sorted_scores = np.sort(scores)[::-1]
print(f"სორტირებული (კლებადი): {sorted_scores}")

# 80-ზე მეტი ქულების რაოდენობა
excellent = np.count_nonzero(scores >= 80)
print(f"\nსარჩულო ქულები (≥80): {excellent}")

# 60-დან 80-მდე ქულების რაოდენობა
good = np.count_nonzero((scores >= 60) & (scores < 80))
print(f"კარგი ქულები (60-80): {good}")

# 60-ზე ნაკლები ქულების რაოდენობა
poor = np.count_nonzero(scores < 60)
print(f"ცუდი ქულები (<60): {poor}")

# სარჩულო სტუდენტების ინდექსი
excellent_indices = np.where(scores >= 80)[0]
print(f"\nსარჩულო სტუდენტების ინდექსი: {excellent_indices}")
print(f"მათი ქულები: {scores[excellent_indices]}")

# ============================================================
# 10. np.searchsorted (დასახელების მოსაძებნად)
# ============================================================

print("\n\n" + "=" * 70)
print("10. np.searchsorted (სახელმძღვანელო ძებნა)")
print("=" * 70)

sorted_arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
print(f"\nსორტირებული მასივი: {sorted_arr}")

# 35 სად უნდა ჩასაბნეთ?
position = np.searchsorted(sorted_arr, 35)
print(f"\n35-ის პოზიცია: {position}")

# რამდენი ელემენტი ნაკლებია 35-ზე?
count_less_35 = np.searchsorted(sorted_arr, 35)
print(f"35-ზე ნაკლები ელემენტების რაოდენობა: {count_less_35}")

# ============================================================
# 11. ხელმძღვანელი ცხრილი
# ============================================================

print("\n\n" + "=" * 70)
print("ხელმძღვანელი ცხრილი")
print("=" * 70)

table = """
┌──────────────────────┬────────────────────────────────────────┐
│ ფუნქცია              │ აღწერა                                 │
├──────────────────────┼────────────────────────────────────────┤
│ np.sort()            │ მასივის სორტირება (ახალი მასივი)      │
│ np.argsort()         │ სორტირებული ინდექსები                 │
│ np.where(condition)  │ მდგომარეობის დამაკმაყოფილებელი        │
│                      │ ელემენტების ინდექსი                    │
│ np.count_nonzero()   │ არანულოვანი ელემენტების დათვლა       │
│ np.sum(condition)    │ პირობის დამაკმაყოფილებელი სიგრძე      │
│ np.searchsorted()    │ დასახელების მოხედვით ხელმძღვანელი     │
│                      │ ძებნა                                  │
└──────────────────────┴────────────────────────────────────────┘
"""
print(table)

სორტირება, ძებნა და დათვლა


1. სორტირება (Sorting)

ორიგინალური მასივი: [45 12 78 23 56 89 34 67 11 90]
Sorted (ascending): [11 12 23 34 45 56 67 78 89 90]
ორიგინალური (უცვლელი): [45 12 78 23 56 89 34 67 11 90]
Sorted (descending): [90 89 78 67 56 45 34 23 12 11]


2. სორტირება თავდაპირველი ინდექსებით

ორიგინალური მასივი: [45 12 78 23 56]
Sorted Indices: [1 3 0 4 2]
ახსნა: 1 ინდექსে ყველაზე პატარა (12)
Sorted Values: [12 23 45 56 78]
Sorted Indices (descending): [2 4 0 3 1]


3. 2D მასივის სორტირება

ორიგინალური მატრიცა:
[[45 12 78]
 [23 56 89]
 [34 67 11]]

რიგების სორტირება (axis=1):
[[12 45 78]
 [23 56 89]
 [11 34 67]]

სვეტების სორტირება (axis=0):
[[23 12 11]
 [34 56 78]
 [45 67 89]]


4. ძებნა (np.where)

მასივი: [10 25 30 15 50 20 45 35 60  5]

30-ზე მეტი ელემენტების ინდექსი: [4 6 7 8]
30-ზე მეტი ელემენტები: [50 45 35 60]

20-ზე ნაკლები ელემენტების ინდექსი: [0 3 9]
20-ის ტოლი ელემენტების ინდექსი: [5]
30-სა და 50-ს შორის: [6 7]


5. რთული პირობები (np.where)

მასივი: [ 10  20  30

## 6. მასივის ელემენტების შეცვლა, მინიჭება და კოპირება
- **შეცვლა და მინიჭება:**  
  - შექმენით numpy მასივი.
  - მიიღეთ მასივი ნაწილი (slice) და შეიტანეთ ცვლილებები ამ ნაწილში. დააკვირდით, როგორ შეიცვლება წამოღებული ნაწილი.

- **კოპირება:**  
  - შეაქმეთ shallow და deep კოპი.
  - დაადასტურეთ ცვლილებების შორის განსხვავებები: შეცვალეთ deep კოპი და დააკვირდით, რომ თავდაპირველი მასივი უცვლელად რჩება.

In [ ]:
import numpy as np

print("=" * 70)
print("მასივის ელემენტების შეცვლა, მინიჭება და კოპირება")
print("=" * 70)

# ============================================================
# 1. შეცვლა და მინიჭება (Slice და View)
# ============================================================

print("\n\n" + "=" * 70)
print("1. შეცვლა და მინიჭება (Slice და View)")
print("=" * 70)

# ორიგინალური მასივი
array_original = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(f"\nორიგინალური მასივი: {array_original}")

# Slice (ნაწილი) - ეს არის VIEW, არა კოპია!
array_slice = array_original[2:6]
print(f"Slice (ელემენტი 2-5): {array_slice}")
print(f"შენიშვნა: Slice არის VIEW ორიგინალური მასივის!")

# Slice-ის შეცვლა
print("\n--- Slice-ის შეცვლა ---")
array_slice[0] = 100
array_slice[1] = 200

print(f"Slice შეცვლის შემდეგ: {array_slice}")
print(f"ორიგინალური მასივი (შეცვლილი!): {array_original}")
print(f"⚠️  ორიგინალური მასივი შეიცვალა, რადგან Slice არის VIEW!")

# ============================================================
# 2. მეორე განზომილების Slice
# ============================================================

print("\n\n" + "=" * 70)
print("2. 2D მასივის Slice და შეცვლა")
print("=" * 70)

matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

print(f"\nორიგინალური მატრიცა:\n{matrix}")

# რიგის Slice
row_slice = matrix[1]
print(f"\nმეორე რიგი (Slice): {row_slice}")

# სვეტის Slice
col_slice = matrix[:, 2]
print(f"მესამე სვეტი (Slice): {col_slice}")

# 2x2 ქვე-მატრიცა
sub_matrix = matrix[1:3, 1:3]
print(f"2x2 ქვე-მატრიცა:\n{sub_matrix}")

# ქვე-მატრიცის შეცვლა
print("\n--- ქვე-მატრიცის შეცვლა ---")
sub_matrix[:] = 999
print(f"ქვე-მატრიცის შეცვლის შემდეგ:\n{sub_matrix}")
print(f"ორიგინალური მატრიცა (შეცვლილი!):\n{matrix}")

# ============================================================
# 3. Shallow Copy
# ============================================================

print("\n\n" + "=" * 70)
print("3. Shallow Copy (არაღრმა კოპია)")
print("=" * 70)

# ახალი მასივი
array1 = np.array([1, 2, 3, 4, 5])
print(f"\nორიგინალური მასივი: {array1}")
print(f"ID: {id(array1)}")

# Shallow Copy - გამოიყენება .view()
array1_shallow = array1.view()
print(f"\nShallow Copy: {array1_shallow}")
print(f"ID: {id(array1_shallow)}")
print(f"სხვადსხვა ობიექტი? {array1 is not array1_shallow}")

# Shallow Copy-ის შეცვლა
print("\n--- Shallow Copy-ის შეცვლა ---")
array1_shallow[0] = 100
print(f"Shallow Copy შეცვლის შემდეგ: {array1_shallow}")
print(f"ორიგინალური მასივი (შეცვლილი!): {array1}")
print(f"⚠️  ორიგინალური მასივი შეიცვალა, რადგან Shallow Copy იზიარებს მონაცემებს!")

# ============================================================
# 4. Deep Copy
# ============================================================

print("\n\n" + "=" * 70)
print("4. Deep Copy (გრმა კოპია)")
print("=" * 70)

# ახალი მასივი
array2 = np.array([10, 20, 30, 40, 50])
print(f"\nორიგინალური მასივი: {array2}")
print(f"ID: {id(array2)}")

# Deep Copy - გამოიყენება .copy()
array2_deep = array2.copy()
print(f"\nDeep Copy: {array2_deep}")
print(f"ID: {id(array2_deep)}")
print(f"სხვადსხვა ობიექტი? {array2 is not array2_deep}")

# Deep Copy-ის შეცვლა
print("\n--- Deep Copy-ის შეცვლა ---")
array2_deep[0] = 999
array2_deep[2] = 888
print(f"Deep Copy შეცვლის შემდეგ: {array2_deep}")
print(f"ორიგინალური მასივი (უცვლელი!): {array2}")
print(f"✅ ორიგინალური მასივი უცვლელი რჩება!")

# ============================================================
# 5. ვიზუალური შედარება: View vs Shallow vs Deep
# ============================================================

print("\n\n" + "=" * 70)
print("5. ვიზუალური შედარება: View vs Shallow vs Deep")
print("=" * 70)

original = np.array([1, 2, 3, 4, 5])
print(f"\nორიგინალური მასივი: {original}")

# View
view_copy = original[:]
print(f"View (original[:]): {view_copy}")

# Shallow
shallow_copy = original.view()
print(f"Shallow (.view()): {shallow_copy}")

# Deep
deep_copy = original.copy()
print(f"Deep (.copy()): {deep_copy}")

# შეცვლა
print("\n--- ყველა მასივის შეცვლა ---")
original[0] = 111
view_copy[1] = 222
shallow_copy[2] = 333
deep_copy[3] = 444

print(f"\nორიგინალური: {original}")
print(f"View: {view_copy}")
print(f"Shallow: {shallow_copy}")
print(f"Deep: {deep_copy}")

# ============================================================
# 6. 2D მასივის კოპირება
# ============================================================

print("\n\n" + "=" * 70)
print("6. 2D მასივის კოპირება")
print("=" * 70)

matrix_original = np.array([[1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9]])
print(f"\nორიგინალური მატრიცა:\n{matrix_original}")

# Shallow Copy
matrix_shallow = matrix_original.view()
print(f"\nShallow Copy:\n{matrix_shallow}")

# Deep Copy
matrix_deep = matrix_original.copy()
print(f"\nDeep Copy:\n{matrix_deep}")

# შეცვლა
print("\n--- შეცვლა ---")
matrix_shallow[0, 0] = 100
matrix_deep[0, 0] = 200

print(f"\nორიგინალური (შეცვლილი shallow-ის მხრიდან):\n{matrix_original}")
print(f"Shallow:\n{matrix_shallow}")
print(f"Deep (უცვლელი):\n{matrix_deep}")

# ============================================================
# 7. დეტალური ცხრილი: მეხსიერება და მონაცემები
# ============================================================

print("\n\n" + "=" * 70)
print("7. დეტალური შედარება: მეხსიერება")
print("=" * 70)

arr = np.array([1, 2, 3, 4, 5])
print(f"\nორიგინალური მასივი: {arr}")
print(f"  ID: {id(arr)}")
print(f"  data pointer: {arr.data}")
print(f"  owns data: {arr.flags['OWNDATA']}")

view = arr.view()
print(f"\nView:")
print(f"  ID: {id(view)}")
print(f"  data pointer: {view.data}")
print(f"  owns data: {view.flags['OWNDATA']}")
print(f"  იგივე მონაცემები? {arr.data == view.data}")

copy = arr.copy()
print(f"\nCopy:")
print(f"  ID: {id(copy)}")
print(f"  data pointer: {copy.data}")
print(f"  owns data: {copy.flags['OWNDATA']}")
print(f"  იგივე მონაცემები? {arr.data == copy.data}")

# ============================================================
# 8. რეალური მაგალითი: ფილტრაცია
# ============================================================

print("\n\n" + "=" * 70)
print("8. რეალური მაგალითი: ფილტრაცია და შეცვლა")
print("=" * 70)

data = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(f"\nორიგინალური მონაცემები: {data}")

# 50-ზე მეტი ელემენტები
mask = data > 50
filtered = data[mask]
print(f"\n50-ზე მეტი (Slice): {filtered}")
print(f"ეს არის View? {filtered.base is data or filtered.base is None}")

# გადაქცევა 0-ში
filtered[:] = 0
print(f"\nფილტრირებული შეცვლის შემდეგ: {filtered}")
print(f"ორიგინალური (შეიცვალა!): {data}")

# ============================================================
# 9. ჩაბნელებული შედარება
# ============================================================

print("\n\n" + "=" * 70)
print("9. ჯამური შედარება: Reference vs View vs Copy")
print("=" * 70)

original = np.array([1, 2, 3])
print(f"\nორიგინალური: {original}")

# Reference (Python ცვლადი)
reference = original  # ეს არის იგივე ობიექტი!
reference[0] = 100
print(f"\nReference მინიჭების შემდეგ:")
print(f"  original: {original} (შეიცვალა!)")
print(f"  reference: {reference}")
print(f"  იგივე ობიექტი? {original is reference}")

# View
original2 = np.array([1, 2, 3])
view = original2.view()
view[0] = 200
print(f"\nView მინიჭების შემდეგ:")
print(f"  original2: {original2} (შეიცვალა!)")
print(f"  view: {view}")
print(f"  იგივე ობიექტი? {original2 is view}")

# Copy
original3 = np.array([1, 2, 3])
copy = original3.copy()
copy[0] = 300
print(f"\nCopy მინიჭების შემდეგ:")
print(f"  original3: {original3} (უცვლელი!)")
print(f"  copy: {copy}")
print(f"  იგივე ობიექტი? {original3 is copy}")

# ============================================================
# ხელმძღვანელი ცხრილი
# ============================================================

print("\n\n" + "=" * 70)
print("ხელმძღვანელი ცხრილი")
print("=" * 70)

table = """
┌─────────────────┬──────────────┬──────────────────┬──────────────────┐
│ მეთოდი          │ ახალი ობი?  │ მონაცემი იზიარდა? │ შეცვლა ზეგავლენა  │
├─────────────────┼──────────────┼──────────────────┼──────────────────┤
│ Reference       │ არა          │ იზიარდა          │ ✅ შეიცვლება      │
│ (=)             │              │                  │                  │
├─────────────────┼──────────────┼──────────────────┼──────────────────┤
│ Slice           │ ✅ დიახ      │ იზიარდა (VIEW)   │ ✅ შეიცვლება      │
│ ([i:j])         │              │                  │                  │
├─────────────────┼──────────────┼──────────────────┼──────────────────┤
│ Shallow Copy    │ ✅ დიახ      │ იზიარდა (VIEW)   │ ✅ შეიცვლება      │
│ (.view())       │              │                  │                  │
├─────────────────┼──────────────┼──────────────────┼──────────────────┤
│ Deep Copy       │ ✅ დიახ      │ არა (კოპია)      │ ❌ უცვლელი        │
│ (.copy())       │              │                  │                  │
└─────────────────┴──────────────┴──────────────────┴──────────────────┘
"""
print(table)

მასივის ელემენტების შეცვლა, მინიჭება და კოპირება


1. შეცვლა და მინიჭება (Slice და View)

ორიგინალური მასივი: [ 1  2  3  4  5  6  7  8  9 10]
Slice (ელემენტი 2-5): [3 4 5 6]
შენიშვნა: Slice არის VIEW ორიგინალური მასივის!

--- Slice-ის შეცვლა ---
Slice შეცვლის შემდეგ: [100 200   5   6]
ორიგინალური მასივი (შეცვლილი!): [  1   2 100 200   5   6   7   8   9  10]
⚠️  ორიგინალური მასივი შეიცვალა, რადგან Slice არის VIEW!


2. 2D მასივის Slice და შეცვლა

ორიგინალური მატრიცა:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

მეორე რიგი (Slice): [5 6 7 8]
მესამე სვეტი (Slice): [ 3  7 11 15]
2x2 ქვე-მატრიცა:
[[ 6  7]
 [10 11]]

--- ქვე-მატრიცის შეცვლა ---
ქვე-მატრიცის შეცვლის შემდეგ:
[[999 999]
 [999 999]]
ორიგინალური მატრიცა (შეცვლილი!):
[[  1   2   3   4]
 [  5 999 999   8]
 [  9 999 999  12]
 [ 13  14  15  16]]


3. Shallow Copy (არაღრმა კოპია)

ორიგინალური მასივი: [1 2 3 4 5]
ID: 135156228748560

Shallow Copy: [1 2 3 4 5]
ID: 135156240507184
სხვადსხვა ობიექტი? True

--- Shallow Cop

## 7. დამატებითი – ფუნქციის შექმნა numpy მასივებზე
- **ფორმულა ფუნქცია:**  
  დაწერეთ ფუნქცია, რომელიც იღებს numpy მასივს და აბრუნებს იგივე ზომის ახალ მასივს, სადაც თითოეული ელემენტი შეიცვლება მისი მნიშვნელობის და მთლიანი მასივის საშუალო მნიშვნელობის სხვაობით.

In [ ]:
import numpy as np

def deviation_from_mean(arr):
    """
    numpy მასივის თითოეული ელემენტის გადახრა საშუალოდან.

    ფორმულა: deviation = elem - mean(arr)

    პარამეტრი:
        arr: numpy array (1D ან 2D)

    დაბრუნება:
        იგივე ზომის numpy array გადახრებით
    """
    # საშუალო გამოთვლა
    mean = np.mean(arr)

    # გადახრა საშუალოდან
    deviation = arr - mean

    return deviation


print("=" * 60)
print("ფორმულა ფუნქცია: ელემენტის გადახრა საშუალოდან")
print("=" * 60)

# მაგალითი 1: 1D მასივი
print("\n\nმაგალითი 1: 1D მასივი")
print("-" * 60)

array1 = np.array([10, 20, 30, 40, 50])
print(f"ორიგინალური მასივი: {array1}")
print(f"საშუალო: {np.mean(array1)}")

deviation1 = deviation_from_mean(array1)
print(f"გადახრა საშუალოდან: {deviation1}")

# შემოწმება
print(f"\nდეტალი:")
mean1 = np.mean(array1)
for i, elem in enumerate(array1):
    dev = elem - mean1
    print(f"  {elem} - {mean1} = {dev}")

# მაგალითი 2: უარყოფითი რიცხვები
print("\n\nმაგალითი 2: უარყოფითი რიცხვები")
print("-" * 60)

array2 = np.array([-10, -5, 0, 5, 10])
print(f"ორიგინალური მასივი: {array2}")
print(f"საშუალო: {np.mean(array2)}")

deviation2 = deviation_from_mean(array2)
print(f"გადახრა საშუალოდან: {deviation2}")

# მაგალითი 3: შემთხვევითი რიცხვები
print("\n\nმაგალითი 3: შემთხვევითი რიცხვები")
print("-" * 60)

np.random.seed(42)
array3 = np.random.randint(1, 100, size=10)
print(f"ორიგინალური მასივი: {array3}")
print(f"საშუალო: {np.mean(array3):.2f}")

deviation3 = deviation_from_mean(array3)
print(f"გადახრა საშუალოდან: {np.round(deviation3, 2)}")

# მაგალითი 4: 2D მასივი
print("\n\nმაგალითი 4: 2D მასივი (5x3)")
print("-" * 60)

array4 = np.array([[10, 20, 30],
                   [15, 25, 35],
                   [20, 30, 40],
                   [25, 35, 45],
                   [30, 40, 50]])

print(f"ორიგინალური მასივი:\n{array4}")
print(f"საშუალო: {np.mean(array4):.2f}")

deviation4 = deviation_from_mean(array4)
print(f"გადახრა საშუალოდან:\n{np.round(deviation4, 2)}")

# მაგალითი 5: დეტალური ანალიზი
print("\n\nმაგალითი 5: დეტალური ანალიზი")
print("-" * 60)

array5 = np.array([5, 10, 15, 20, 25])
print(f"ორიგინალური მასივი: {array5}")

mean5 = np.mean(array5)
print(f"საშუალო (μ): {mean5}")

deviation5 = deviation_from_mean(array5)
print(f"გადახრა: {deviation5}")

# გადახრის ჯამი უნდა იყოს 0
print(f"\nგადახრის ჯამი: {np.sum(deviation5):.10f} (უნდა იყოს ≈ 0)")

# გადახრის საშუალო უნდა იყოს 0
print(f"გადახრის საშუალო: {np.mean(deviation5):.10f} (უნდა იყოს ≈ 0)")

# მაგალითი 6: სხვადასხვა ზომის მასივი
print("\n\nმაგალითი 6: სხვადასხვა ზომის მასივი")
print("-" * 60)

# 3D მასივი
array6 = np.arange(1, 25).reshape(2, 3, 4)
print(f"ორიგინალური 3D მასივი (2x3x4):\n{array6}")
print(f"საშუალო: {np.mean(array6):.2f}")

deviation6 = deviation_from_mean(array6)
print(f"\nგადახრა საშუალოდან:\n{np.round(deviation6, 2)}")

# მაგალითი 7: პოპულაციის მაგალითით
print("\n\nმაგალითი 7: რეალური მაგალითი - სტუდენტების ქულები")
print("-" * 60)

scores = np.array([65, 70, 75, 80, 85, 90, 95])
print(f"ქულები: {scores}")
print(f"საშუალო ქულა: {np.mean(scores):.2f}")

deviation_scores = deviation_from_mean(scores)
print(f"გადახრა საშუალოდან: {np.round(deviation_scores, 2)}")

print("\nინტერპრეტაცია:")
for i, (score, dev) in enumerate(zip(scores, deviation_scores)):
    if dev > 0:
        print(f"  სტუდენტი {i+1}: {score} (საშუალოზე {dev:.2f} მეტი)")
    elif dev < 0:
        print(f"  სტუდენტი {i+1}: {score} (საშუალოზე {abs(dev):.2f} ნაკლები)")
    else:
        print(f"  სტუდენტი {i+1}: {score} (საშუალოთან ტოლი)")

# მაგალითი 8: სტანდარტიზაციასთან შედარება
print("\n\nმაგალითი 8: გადახრა VS სტანდარტიზაცია")
print("-" * 60)

array8 = np.array([10, 20, 30, 40, 50])
print(f"ორიგინალური მასივი: {array8}")

# მხოლოდ გადახრა
deviation8 = deviation_from_mean(array8)
print(f"გადახრა საშუალოდან: {deviation8}")

# სტანდარტიზაცია (გადახრა / სტდ)
standardized8 = deviation8 / np.std(array8)
print(f"სტანდარტიზაცია: {np.round(standardized8, 4)}")

print("\nსხვაობა:")
print("  გადახრა: ელემენტი - საშუალო")
print("  სტანდარტიზაცია: (ელემენტი - საშუალო) / სტდ")

ფორმულა ფუნქცია: ელემენტის გადახრა საშუალოდან


მაგალითი 1: 1D მასივი
------------------------------------------------------------
ორიგინალური მასივი: [10 20 30 40 50]
საშუალო: 30.0
გადახრა საშუალოდან: [-20. -10.   0.  10.  20.]

დეტალი:
  10 - 30.0 = -20.0
  20 - 30.0 = -10.0
  30 - 30.0 = 0.0
  40 - 30.0 = 10.0
  50 - 30.0 = 20.0


მაგალითი 2: უარყოფითი რიცხვები
------------------------------------------------------------
ორიგინალური მასივი: [-10  -5   0   5  10]
საშუალო: 0.0
გადახრა საშუალოდან: [-10.  -5.   0.   5.  10.]


მაგალითი 3: შემთხვევითი რიცხვები
------------------------------------------------------------
ორიგინალური მასივი: [52 93 15 72 61 21 83 87 75 75]
საშუალო: 63.40
გადახრა საშუალოდან: [-11.4  29.6 -48.4   8.6  -2.4 -42.4  19.6  23.6  11.6  11.6]


მაგალითი 4: 2D მასივი (5x3)
------------------------------------------------------------
ორიგინალური მასივი:
[[10 20 30]
 [15 25 35]
 [20 30 40]
 [25 35 45]
 [30 40 50]]
საშუალო: 30.00
გადახრა საშუალოდან:
[[-20. -10.   0.]


## 8. 5x5 მატრიცა და სტანდარტიზაციის პროცესი

- **შექმენით 5x5 მატრიცა:**  
  შეავსეთ მატრიცა მთელი რიცხვებით (მაგ., `np.random.randint`-ის გამოყენებით).

- **სტანდარტიზაცია:**  
  გააკეთეთ სტანდარტიზაციის პროცესი, რაც ნიშნავს, რომ თითოეული ელემენტს გამოაკლდება მატრიცის საშუალო (mean) და ეს სხვაობა შეფარდდება მატრიცის სტანდარტულ გადახრასთან (standard deviation).  
  ფორმულით:

  
  $\text{standardized\_elem} = \frac{elem - \mu}{\sigma}$

  
  სადაც $\mu$ არის მატრიცის საშუალო და $\sigma$ – სტანდარტული გადახრა.

In [ ]:
import numpy as np

def standardize_matrix(matrix):
    """
    მატრიცის სტანდარტიზაცია (Z-score normalization).

    ფორმულა: standardized = (elem - mean) / std

    პარამეტრი:
        matrix: numpy array

    დაბრუნება:
        სტანდარტიზირებული numpy array
    """
    # საშუალო (mean)
    mean = np.mean(matrix)

    # სტანდარტული გადახრა (standard deviation)
    std = np.std(matrix)

    # სტანდარტიზაცია
    standardized = (matrix - mean) / std

    return standardized, mean, std


print("=" * 60)
print("5x5 მატრიცა და სტანდარტიზაციის პროცესი")
print("=" * 60)

# 5x5 მატრიცა შემთხვევითი მთელი რიცხვებით
np.random.seed(42)
matrix = np.random.randint(10, 100, size=(5, 5))

print(f"\nორიგინალური 5x5 მატრიცა:\n{matrix}")
print(f"ფორმა: {matrix.shape}")

# სტატისტიკა ორიგინალური მატრიცის
print(f"\nორიგინალური მატრიცის სტატისტიკა:")
print(f"  საშუალო (μ): {np.mean(matrix):.2f}")
print(f"  სტანდარტული გადახრა (σ): {np.std(matrix):.2f}")
print(f"  მინიმალური: {np.min(matrix)}")
print(f"  მაქსიმალური: {np.max(matrix)}")

# სტანდარტიზაცია
standardized, mean, std = standardize_matrix(matrix)

print(f"\nსტანდარტიზირებული მატრიცა:\n{standardized}")

# სტანდარტიზირებული მატრიცის სტატისტიკა
print(f"\nსტანდარტიზირებული მატრიცის სტატისტიკა:")
print(f"  საშუალო (μ): {np.mean(standardized):.10f} (≈ 0)")
print(f"  სტანდარტული გადახრა (σ): {np.std(standardized):.2f} (≈ 1)")
print(f"  მინიმალური: {np.min(standardized):.2f}")
print(f"  მაქსიმალური: {np.max(standardized):.2f}")

print("\n" + "=" * 60)
print("დამატებითი: ელემენტების დეტალური გამოთვლა")
print("=" * 60)

print(f"\nორიგინალური მატრიცის პირველი რიგი: {matrix[0]}")
print(f"\nემენტების გამოთვლა (μ={mean:.2f}, σ={std:.2f}):")

for i, elem in enumerate(matrix[0]):
    standardized_elem = (elem - mean) / std
    print(f"  elem[{i}] = {elem}")
    print(f"    ({elem} - {mean:.2f}) / {std:.2f} = {standardized_elem:.4f}")

print(f"\nსტანდარტიზირებული პირველი რიგი: {standardized[0]}")

print("\n" + "=" * 60)
print("მაგალითი 2: სხვადასხვა მატრიცა")
print("=" * 60)

# უარყოფითი და დიდი რიცხვები
np.random.seed(99)
matrix2 = np.random.randint(0, 200, size=(5, 5))

print(f"\nორიგინალური მატრიცა:\n{matrix2}")
print(f"საშუალო: {np.mean(matrix2):.2f}, სტд: {np.std(matrix2):.2f}")

standardized2, mean2, std2 = standardize_matrix(matrix2)

print(f"\nსტანდარტიზირებული მატრიცა:\n{standardized2}")
print(f"საშუალო: {np.mean(standardized2):.10f}, სტd: {np.std(standardized2):.2f}")

print("\n" + "=" * 60)
print("მაგალითი 3: NumPy-ის ჩაშენებული ფუნქციით")
print("=" * 60)

# sklearn-ის მსგავსი (თუ გსურთ გამოიყენოთ sklearn)
# from sklearn.preprocessing import StandardScaler
# scaler = StandardScaler()
# standardized = scaler.fit_transform(matrix.reshape(-1, 1))

# NumPy-ს ფუნქციებით
print("\nNumPy ფუნქციების გამოყენება:")
print(f"  np.mean(matrix): {np.mean(matrix):.2f}")
print(f"  np.std(matrix): {np.std(matrix):.2f}")
print(f"  np.var(matrix): {np.var(matrix):.2f} (variance = std²)")

print("\n" + "=" * 60)
print("მაგალითი 4: რიგის, სვეტის ან რო-ს მხრივ სტანდარტიზაცია")
print("=" * 60)

matrix4 = np.array([[10, 20, 30],
                    [15, 25, 35],
                    [20, 30, 40]])

print(f"ორიგინალური მატრიცა:\n{matrix4}")

# მთელი მატრიცის სტანდარტიზაცია
standardized_all = (matrix4 - np.mean(matrix4)) / np.std(matrix4)
print(f"\nმთელი მატრიცის სტანდარტიზაცია:\n{standardized_all}")

# რიგების მხრივ სტანდარტიზაცია (axis=1)
standardized_rows = (matrix4 - np.mean(matrix4, axis=1, keepdims=True)) / \
                    np.std(matrix4, axis=1, keepdims=True)
print(f"\nრიგების მხრივ სტანდარტიზაცია (axis=1):\n{standardized_rows}")

# სვეტების მხრივ სტანდარტიზაცია (axis=0)
standardized_cols = (matrix4 - np.mean(matrix4, axis=0, keepdims=True)) / \
                    np.std(matrix4, axis=0, keepdims=True)
print(f"\nსვეტების მხრივ სტანდარტიზაცია (axis=0):\n{standardized_cols}")

print("\n" + "=" * 60)
print("მაგალითი 5: ვიზუალური შედარება")
print("=" * 60)

# ხელოვნური მონაცემი
data = np.array([[100, 200, 300],
                 [50, 100, 150],
                 [200, 400, 600]])

print(f"ორიგინალური:\n{data}")
print(f"დიაპაზონი: {np.min(data)} - {np.max(data)}")

standardized_data = (data - np.mean(data)) / np.std(data)
print(f"\nსტანდარტიზირებული:\n{standardized_data}")
print(f"დიაპაზონი: {np.min(standardized_data):.2f} - {np.max(standardized_data):.2f}")

# ნორმალიზირებული (სხვა მეთოდი)
normalized_data = (data - np.min(data)) / (np.max(data) - np.min(data))
print(f"\nნორმალიზირებული (Min-Max):\n{normalized_data}")
print(f"დიაპაზონი: {np.min(normalized_data):.2f} - {np.max(normalized_data):.2f}")

5x5 მატრიცა და სტანდარტიზაციის პროცესი

ორიგინალური 5x5 მატრიცა:
[[61 24 81 70 30]
 [92 96 84 84 97]
 [33 12 31 62 11]
 [97 39 47 11 73]
 [69 30 42 85 67]]
ფორმა: (5, 5)

ორიგინალური მატრიცის სტატისტიკა:
  საშუალო (μ): 57.12
  სტანდარტული გადახრა (σ): 28.41
  მინიმალური: 11
  მაქსიმალური: 97

სტანდარტიზირებული მატრიცა:
[[ 0.13657015 -1.16577406  0.84053999  0.45335658 -0.9545831 ]
 [ 1.2277234   1.36851737  0.94613547  0.94613547  1.40371586]
 [-0.84898763 -1.58815596 -0.91938461  0.17176864 -1.62335445]
 [ 1.40371586 -0.63779668 -0.35620874 -1.62335445  0.55895205]
 [ 0.41815809 -0.9545831  -0.5322012   0.98133396  0.3477611 ]]

სტანდარტიზირებული მატრიცის სტატისტიკა:
  საშუალო (μ): 0.0000000000 (≈ 0)
  სტანდარტული გადახრა (σ): 1.00 (≈ 1)
  მინიმალური: -1.62
  მაქსიმალური: 1.40

დამატებითი: ელემენტების დეტალური გამოთვლა

ორიგინალური მატრიცის პირველი რიგი: [61 24 81 70 30]

ემენტების გამოთვლა (μ=57.12, σ=28.41):
  elem[0] = 61
    (61 - 57.12) / 28.41 = 0.1366
  elem[1] = 24
    (24 - 5

## 9. ნორმალიზებული numpy array-ს დაბრუნება ფუნქციით

- დაწერეთ ფუნქცია, რომელსაც გადაეცემა numpy array და რომელიც აბრუნებს ნორმალიზირებულ მასივს.
  
- **ნორმალიზაციის პროცესი:**  
  თითოეული ელემენტი გარდაიქმნება შემდეგი ფორმულით:

  
$ \text{normalized\_elem} = \frac{elem - \min(arr)}{\max(arr) - \min(arr)} $

  სადაც $\min(arr)$ და $\max(arr)$ არის მოცემული მასივის მინიმალური და მაქსიმალური მნიშვნელობები.

In [ ]:
import numpy as np

def normalize_array(arr):
    """
    NumPy მასივის ნორმალიზაცია Min-Max scaling გამოყენებით

    ფორმულა: normalized = (elem - min(arr)) / (max(arr) - min(arr))

    პარამეტრი:
        arr: numpy array

    დაბრუნება:
        ნორმალიზირებული numpy array (0-დან 1-მდე)
    """
    arr = np.array(arr)  # დარწმუნებული რომ array-ია

    # მინიმალური და მაქსიმალური მნიშვნელობები
    min_val = np.min(arr)
    max_val = np.max(arr)

    # ნორმალიზაცია
    normalized = (arr - min_val) / (max_val - min_val)

    return normalized


# სატესტო კოდი
print("=" * 50)
print("NumPy Array ნორმალიზაცია")
print("=" * 50)

# მაგალითი 1: მარტივი array
array1 = np.array([10, 20, 30, 40, 50])
print(f"\nორიგინალური array 1: {array1}")
print(f"ნორმალიზებული array 1: {normalize_array(array1)}")

# მაგალითი 2: უარყოფითი რიცხვები
array2 = np.array([-5, 0, 5, 10, 15])
print(f"\nორიგინალური array 2: {array2}")
print(f"ნორმალიზებული array 2: {normalize_array(array2)}")

# მაგალითი 3: შემთხვევითი რიცხვები
array3 = np.random.randint(0, 100, size=10)
print(f"\nორიგინალური array 3: {array3}")
print(f"ნორმალიზებული array 3: {normalize_array(array3)}")

# მაგალითი 4: დიაპაზონი 1-100
array4 = np.array([15, 30, 45, 60, 75, 90])
print(f"\nორიგინალური array 4: {array4}")
normalized4 = normalize_array(array4)
print(f"ნორმალიზებული array 4: {normalized4}")

# შემოწმება: მინიმალური და მაქსიმალური
print(f"\nნორმალიზებული მინ: {np.min(normalized4)}")
print(f"ნორმალიზებული მაქს: {np.max(normalized4)}")

print("\n" + "=" * 50)
print("დამატებითი: 2D მასივის ნორმალიზაცია")
print("=" * 50)

# 2D მასივი
array_2d = np.array([[10, 20, 30],
                     [40, 50, 60],
                     [70, 80, 90]])
print(f"\nორიგინალური 2D array:\n{array_2d}")

# მთელი 2D მასივი ნორმალიზაცია
normalized_2d = normalize_array(array_2d.flatten()).reshape(array_2d.shape)
print(f"\nნორმალიზებული 2D array:\n{normalized_2d}")

# ან მხოლოდ flatten
print(f"\nნორმალიზებული (flat):\n{normalize_array(array_2d.flatten())}")

NumPy Array ნორმალიზაცია

ორიგინალური array 1: [10 20 30 40 50]
ნორმალიზებული array 1: [0.   0.25 0.5  0.75 1.  ]

ორიგინალური array 2: [-5  0  5 10 15]
ნორმალიზებული array 2: [0.   0.25 0.5  0.75 1.  ]

ორიგინალური array 3: [39 88 25 93 98 34 89 46 83 18]
ნორმალიზებული array 3: [0.2625 0.875  0.0875 0.9375 1.     0.2    0.8875 0.35   0.8125 0.    ]

ორიგინალური array 4: [15 30 45 60 75 90]
ნორმალიზებული array 4: [0.  0.2 0.4 0.6 0.8 1. ]

ნორმალიზებული მინ: 0.0
ნორმალიზებული მაქს: 1.0

დამატებითი: 2D მასივის ნორმალიზაცია

ორიგინალური 2D array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

ნორმალიზებული 2D array:
[[0.    0.125 0.25 ]
 [0.375 0.5   0.625]
 [0.75  0.875 1.   ]]

ნორმალიზებული (flat):
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.   ]


## 10. 8x8 მატრიცა და სხვადასხვა ტრანსფორმაციები

შექმენით 8x8 მატრიცა, შეავსეთ იგი რანდომ რიცხვებით, შემდეგ შეასრულეთ შემდეგი ოპერაციები:

### ა) ზედა და ქვედა ნახევრის გაცვლა

- გაცვალეთ მატრიცის ზედა ნახევარი (პირველი 4 რიგი) ქვედა ნახევრი (ბოლო 4 რიგი).


### ბ) ზედა მარცხენა 4x4 კვადრატისა და ქვედა მარჯვენა 4x4 კვადრატის გაცვლა

- 8x8 მატრიცაში, აირჩიეთ:
  - ზედა მარცხენა კვადრატი (პირველი 4 რიგი და პირველი 4 სვეტი)  
  - ქვედა მარჯვენა კვადრატი (ბოლო 4 რიგი და ბოლო 4 სვეტი)
  
  და შემდეგ გაცვალეთ მათი ადგილები.


### გ) სვეტების გაცვლა

- თითოეულ რიგში შეცვალეთ სვეტები. მაგ., 0–1, 2–3, 4–5, 6–7.

In [ ]:

import numpy as np

print("=" * 60)
print("8x8 მატრიცა და სხვადასხვა ტრანსფორმაციები")
print("=" * 60)

# 8x8 მატრიცა შემთხვევითი რიცხვებით
np.random.seed(42)  # განმეორებადი შედეგებისთვის
matrix = np.random.randint(1, 100, size=(8, 8))

print(f"\nორიგინალური 8x8 მატრიცა:\n{matrix}")

print("\n" + "=" * 60)
print("ა) ზედა და ქვედა ნახევრის გაცვლა")
print("=" * 60)

# კოპია ორიგინალური მატრიცის
matrix_a = matrix.copy()

# ზედა ნახევარი (პირველი 4 რიგი)
top_half = matrix_a[:4].copy()

# ქვედა ნახევარი (ბოლო 4 რიგი)
bottom_half = matrix_a[4:].copy()

# გაცვლა
matrix_a[:4] = bottom_half
matrix_a[4:] = top_half

print(f"\nტრანსფორმირებული მატრიცა (ზედა-ქვედა გაცვლილი):\n{matrix_a}")

print("\n" + "=" * 60)
print("ბ) ზედა მარცხენა 4x4 და ქვედა მარჯვენა 4x4 გაცვლა")
print("=" * 60)

# კოპია ორიგინალური მატრიცის
matrix_b = matrix.copy()

# ზედა მარცხენა 4x4 (პირველი 4 რიგი, პირველი 4 სვეტი)
top_left = matrix_b[:4, :4].copy()

# ქვედა მარჯვენა 4x4 (ბოლო 4 რიგი, ბოლო 4 სვეტი)
bottom_right = matrix_b[4:, 4:].copy()

# გაცვლა
matrix_b[:4, :4] = bottom_right
matrix_b[4:, 4:] = top_left

print(f"\nტრანსფორმირებული მატრიცა (კუთხეები გაცვლილი):\n{matrix_b}")

print("\n" + "=" * 60)
print("გ) სვეტების გაცვლა (0↔1, 2↔3, 4↔5, 6↔7)")
print("=" * 60)

# კოპია ორიგინალური მატრიცის
matrix_c = matrix.copy()

# სვეტების გაცვლა
# 0 ↔ 1
matrix_c[:, [0, 1]] = matrix_c[:, [1, 0]]

# 2 ↔ 3
matrix_c[:, [2, 3]] = matrix_c[:, [3, 2]]

# 4 ↔ 5
matrix_c[:, [4, 5]] = matrix_c[:, [5, 4]]

# 6 ↔ 7
matrix_c[:, [6, 7]] = matrix_c[:, [7, 6]]

print(f"\nტრანსფორმირებული მატრიცა (სვეტები გაცვლილი):\n{matrix_c}")

print("\n" + "=" * 60)
print("დამატებითი: უფრო ელეგანტური გზა სვეტების გაცვლისთვის")
print("=" * 60)

# კოპია ორიგინალური მატრიცის
matrix_c_elegant = matrix.copy()

# ყველა წყვილი ერთდროულად
for i in range(0, 8, 2):
    matrix_c_elegant[:, [i, i+1]] = matrix_c_elegant[:, [i+1, i]]

print(f"\nტრანსფორმირებული მატრიცა (ელეგანტური):\n{matrix_c_elegant}")

print("\n" + "=" * 60)
print("შედარება: ყველა ტრანსფორმაცია ვიზუალურად")
print("=" * 60)

# პიტონის format-ით ლამაზი დაბეჭდვა
operations = [
    ("ორიგინალური", matrix),
    ("ა) ზედა-ქვედა გაცვლა", matrix_a),
    ("ბ) კუთხეები გაცვლილი", matrix_b),
    ("გ) სვეტები გაცვლილი", matrix_c)
]

for title, mat in operations:
    print(f"\n{title}:")
    print(mat)

8x8 მატრიცა და სხვადასხვა ტრანსფორმაციები

ორიგინალური 8x8 მატრიცა:
[[52 93 15 72 61 21 83 87]
 [75 75 88 24  3 22 53  2]
 [88 30 38  2 64 60 21 33]
 [76 58 22 89 49 91 59 42]
 [92 60 80 15 62 62 47 62]
 [51 55 64  3 51  7 21 73]
 [39 18  4 89 60 14  9 90]
 [53  2 84 92 60 71 44  8]]

ა) ზედა და ქვედა ნახევრის გაცვლა

ტრანსფორმირებული მატრიცა (ზედა-ქვედა გაცვლილი):
[[92 60 80 15 62 62 47 62]
 [51 55 64  3 51  7 21 73]
 [39 18  4 89 60 14  9 90]
 [53  2 84 92 60 71 44  8]
 [52 93 15 72 61 21 83 87]
 [75 75 88 24  3 22 53  2]
 [88 30 38  2 64 60 21 33]
 [76 58 22 89 49 91 59 42]]

ბ) ზედა მარცხენა 4x4 და ქვედა მარჯვენა 4x4 გაცვლა

ტრანსფორმირებული მატრიცა (კუთხეები გაცვლილი):
[[62 62 47 62 61 21 83 87]
 [51  7 21 73  3 22 53  2]
 [60 14  9 90 64 60 21 33]
 [60 71 44  8 49 91 59 42]
 [92 60 80 15 52 93 15 72]
 [51 55 64  3 75 75 88 24]
 [39 18  4 89 88 30 38  2]
 [53  2 84 92 76 58 22 89]]

გ) სვეტების გაცვლა (0↔1, 2↔3, 4↔5, 6↔7)

ტრანსფორმირებული მატრიცა (სვეტები გაცვლილი):
[[93 52 72 15

## 11. 2D მატრიცის გაყოფა სატრენინგო და სატესტო მონაცემებად

- დაწერეთ ფუნქცია, რომელიც იღებს 2D numpy array-ს და გაყოფს ორ ნაწილად.
  
- **პროცესი:**  
  გაყოფა უნდა მოხდეს რიგების (rows) მიხედვით.  
  მაგალითად, რიგების 80% უნდა იყოს სატრენინგო ნაწილში და 20% – სატესტო.
  
- ფუნქციამ უნდა დააბრუნოს tuple, რომლის პირველი წევრი არის სატრენინგო მონაცემები და მეორე – სატესტო მონაცემები.

In [ ]:
import numpy as np

def train_test_split(array, train_ratio=0.8, random_state=None):
    """
    2D numpy მასივის გაყოფა სატრენინგო და სატესტო მონაცემებად.
    """

    if random_state is not None:
        np.random.seed(random_state)

    num_rows = array.shape[0]
    train_size = int(num_rows * train_ratio)

    indices = np.random.permutation(num_rows)

    train_indices = indices[:train_size]
    test_indices = indices[train_size:]

    train_data = array[train_indices]
    test_data = array[test_indices]

    return train_data, test_data


print("=" * 60)
print("2D მასივის გაყოფა სატრენინგო და სატესტო მონაცემებად")
print("=" * 60)

# მაგალითი 1: მარტივი 2D მასივი
print("\n\nმაგალითი 1: 10x4 მასივი (80-20 გაყოფა)")
print("-" * 60)

array1 = np.arange(1, 41).reshape(10, 4)
print(f"ორიგინალური მასივი (10x4):\n{array1}")
print(f"ფორმა: {array1.shape}")

train1, test1 = train_test_split(array1, train_ratio=0.8, random_state=42)

print(f"\nსატრენინგო მონაცემები ({len(train1)} რიგი):\n{train1}")
print(f"ფორმა: {train1.shape}")

print(f"\nსატესტო მონაცემები ({len(test1)} რიგი):\n{test1}")
print(f"ფორმა: {test1.shape}")

# მაგალითი 2: დიდი მასივი შემთხვევითი მნიშვნელობებით
print("\n\nმაგალითი 2: 100x5 მასივი (70-30 გაყოფა)")
print("-" * 60)

np.random.seed(123)
array2 = np.random.randint(0, 100, size=(100, 5))

print(f"ორიგინალური მასივი: {array2.shape}")
print(f"პირველი 5 რიგი:\n{array2[:5]}")

train2, test2 = train_test_split(array2, train_ratio=0.7, random_state=42)

print(f"\nსატრენინგო მონაცემები: {train2.shape}")
print(f"სატესტო მონაცემები: {test2.shape}")
print(f"თანაფარდობა: {len(train2)}/{len(test2)} = {len(train2)/len(array2)*100:.1f}%/{len(test2)/len(array2)*100:.1f}%")

# მაგალითი 3: სხვადასხვა თანაფარდობა (შესწორებული!)
print("\n\nმაგალითი 3: სხვადასხვა გაყოფის თანაფარდობა")
print("-" * 60)

# შესწორება: np.arange(1, 101) = 100 ელემენტი, reshape(50, 2) = 50x2
array3 = np.arange(1, 101).reshape(50, 2)

print(f"ორიგინალური მასივი: {array3.shape}")

ratios = [0.6, 0.7, 0.8, 0.9]

for ratio in ratios:
    train, test = train_test_split(array3, train_ratio=ratio, random_state=42)
    print(f"გაყოფა {ratio*100:.0f}%-{(1-ratio)*100:.0f}%: "
          f"სატრენინგო={len(train)}, სატესტო={len(test)}")

# მაგალითი 4: ფუნქცია უარყოფითი რიცხვებით
print("\n\nმაგალითი 4: რთული მნიშვნელობებით (უარყოფითი, ათწილადი)")
print("-" * 60)

array4 = np.array([[-5.2, 10.1, 3.5],
                   [-2.1, 8.9, -1.2],
                   [4.3, -6.7, 2.1],
                   [-3.8, 5.4, 7.2],
                   [1.1, 2.2, 3.3],
                   [-9.9, 0.1, -0.5],
                   [6.6, -4.4, 8.8],
                   [2.5, -3.5, 1.5]])

print(f"ორიგინალური მასივი:\n{array4}")

train4, test4 = train_test_split(array4, train_ratio=0.75, random_state=42)

print(f"\nსატრენინგო ({len(train4)} რიგი):\n{train4}")
print(f"\nსატესტო ({len(test4)} რიგი):\n{test4}")

# მაგალითი 5: დეტალური ინფორმაცია
print("\n\nმაგალითი 5: დეტალური ინფორმაცია")
print("-" * 60)

array5 = np.random.randn(200, 3) * 100 + 50

train5, test5 = train_test_split(array5, train_ratio=0.8, random_state=42)

print(f"ორიგინალური მასივი:")
print(f"  ფორმა: {array5.shape}")
print(f"  საშუალო: {np.mean(array5):.2f}")
print(f"  სტანდარტული გადახრა: {np.std(array5):.2f}")

print(f"\nსატრენინგო მონაცემები:")
print(f"  ფორმა: {train5.shape}")
print(f"  საშუალო: {np.mean(train5):.2f}")
print(f"  სტანდარტული გადახრა: {np.std(train5):.2f}")

print(f"\nსატესტო მონაცემები:")
print(f"  ფორმა: {test5.shape}")
print(f"  საშუალო: {np.mean(test5):.2f}")
print(f"  სტანდარტული გადახრა: {np.std(test5):.2f}")

2D მასივის გაყოფა სატრენინგო და სატესტო მონაცემებად


მაგალითი 1: 10x4 მასივი (80-20 გაყოფა)
------------------------------------------------------------
ორიგინალური მასივი (10x4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]
 [33 34 35 36]
 [37 38 39 40]]
ფორმა: (10, 4)

სატრენინგო მონაცემები (8 რიგი):
[[33 34 35 36]
 [ 5  6  7  8]
 [21 22 23 24]
 [ 1  2  3  4]
 [29 30 31 32]
 [ 9 10 11 12]
 [37 38 39 40]
 [17 18 19 20]]
ფორმა: (8, 4)

სატესტო მონაცემები (2 რიგი):
[[13 14 15 16]
 [25 26 27 28]]
ფორმა: (2, 4)


მაგალითი 2: 100x5 მასივი (70-30 გაყოფა)
------------------------------------------------------------
ორიგინალური მასივი: (100, 5)
პირველი 5 რიგი:
[[66 92 98 17 83]
 [57 86 97 96 47]
 [73 32 46 96 25]
 [83 78 36 96 80]
 [68 49 55 67  2]]

სატრენინგო მონაცემები: (70, 5)
სატესტო მონაცემები: (30, 5)
თანაფარდობა: 70/30 = 70.0%/30.0%


მაგალითი 3: სხვადასხვა გაყოფის თანაფარდობა
---------------------------------